# Generated by Django 3.0.8 on 2020-09-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=120)),
                ('FirstName', models.CharField(max_length=120, null=True)),
                ('LastName', models.CharField(max_length=120, null=True)),
                ('NationalID', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('YearsofExp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleID', models.CharField(max_length=120)),
                ('VehicleCapacity', models.IntegerField()),
                ('YearsOfOperation', models.IntegerField()),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JourneyStat', models.CharField(max_length=120)),
                ('JourneyStop', models.CharField(max_length=120)),
                ('Distance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Vehicle')),
            ],
        ),
    ]
