# Generated by Django 3.0.8 on 2020-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20200904_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ProfilePic',
            field=models.ImageField(blank=True, null=True, upload_to='ProilePics/'),
        ),
    ]
