# Generated by Django 3.0.8 on 2020-09-06 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20200906_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='EndTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='JourneyStatus',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='StartTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
