# Generated by Django 3.0.8 on 2020-09-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_auto_20200906_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='Passangers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
