# Generated by Django 3.0.8 on 2020-09-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_journey_passangers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='Passangers',
            new_name='Passengers',
        ),
    ]
