# Generated by Django 3.0.8 on 2020-09-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_auto_20200914_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='StartTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
