# Generated by Django 3.0.8 on 2020-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0013_auto_20200914_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='premium',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=12),
            preserve_default=False,
        ),
    ]
