# Generated by Django 3.0.8 on 2020-09-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_journey_premium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='YearsOfOperation',
            new_name='YearofMan',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ChasisNo',
            field=models.CharField(default=1, max_length=20, verbose_name=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='EngineNo',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='VahicleValue',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=27),
            preserve_default=False,
        ),
    ]
