# Generated by Django 3.0.8 on 2020-09-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_auto_20200915_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='ChasisNo',
            field=models.CharField(max_length=20),
        ),
    ]
