# Generated by Django 3.0.8 on 2020-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0016_auto_20200915_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearlyRate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('DistRate', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
