# Generated by Django 3.0.8 on 2020-09-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0019_auto_20200915_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='Passengers',
        ),
    ]
