# Generated by Django 3.1.3 on 2021-01-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0020_remove_journey_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='driver',
            new_name='Profile',
        ),
    ]
