# Generated by Django 3.1.3 on 2021-01-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0022_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='NationalID',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Surname',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='YearsofExp',
            field=models.IntegerField(null=True),
        ),
    ]
