# Generated by Django 3.1.3 on 2021-03-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0024_companyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='Driver',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.companyprofile'),
        ),
    ]
