# Generated by Django 3.1.3 on 2021-03-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0025_auto_20210331_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
