# Generated by Django 3.1.3 on 2021-04-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0029_auto_20210401_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='ProilePics/'),
        ),
    ]
