# Generated by Django 3.1.3 on 2021-04-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0030_companyprofile_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tlb_licence',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tlb_licence_exp_date',
            field=models.DateField(null=True),
        ),
    ]
