# Generated by Django 3.1.3 on 2021-04-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0031_auto_20210401_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='Duration',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
